chunk_bitrate: 2000000
cloud_password: tapwaysuperadmin
cloud_upload_enabled: true
cloud_upload_url: http://101.47.153.138:8081
cloud_username: tapway
deepstream_api_url: http://47.250.210.53:9002
edge_public_domain: ''
edge_public_ip: ''
encoding_crf: 28
encoding_preset: ultrafast
motion_blur_kernel: 5
motion_cooldown: 3
motion_detection_scale: 1.0
motion_frame_skip: 2
motion_high_fps: 25
motion_low_fps: 1
motion_min_area: 5000
motion_sensitivity: 128
motion_zones: []
pre_record_buffer: 0
rtsp_relay_port: 8554
streams:
- chunk_duration: 5
  chunk_fps: 2
  chunking_enabled: false
  enabled: true
  id: Test2
  name: Camera 192.168.1.102
  rtsp_url: rtsp://orinnano:orinnano@192.168.1.102:554/stream1
  streaming_enabled: true
- chunk_duration: 5
  chunk_fps: 2
  chunking_enabled: false
  enabled: true
  id: Test3
  name: Camera 192.168.1.103
  rtsp_url: rtsp://orinnano:orinnano@192.168.1.103:554/stream1
  streaming_enabled: true
- chunk_duration: 5
  chunk_fps: 2
  chunking_enabled: false
  enabled: true
  id: test
  name: Camera 192.168.1.133
  rtsp_url: rtsp://orinnano:orinnano@192.168.1.133:554/stream1
  streaming_enabled: true
use_hardware_decode: true
use_hardware_encode: true
use_hardware_pipeline: true
zone_mode: all
